# Generated by Django 5.0.2 on 2024-03-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_enduser_is_enduser'),
        ('appointment', '0002_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.enduser'),
        ),
    ]
