# Generated by Django 5.0.2 on 2024-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_enduser_otp_alter_enduser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndUser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_enduser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
