# Generated by Django 5.0.2 on 2024-02-14 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_slot_day_remove_slot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
