# Generated by Django 5.0.2 on 2024-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_slot_end_time_slot_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(related_name='schedules', to='schedule.day')),
                ('shifts', models.ManyToManyField(related_name='schedules', to='schedule.shift')),
            ],
        ),
    ]
